### ISSUE TITLE
Allow for custom `doSort()` implementataions

### ISSUE THREAD

**Issue by mkielar** [drvic10k/bootstrap-sortable#56]
I'd like to use your library for backend-sorting (i.e. click on a header should invoke an AJAX call to backend. To do this, I would implement my own doSort method, the thing is to allow passing this custom method to your controller so it gets called instead of the default one.

**Comment by SamKelly** [comment]
I find this intriguing... I'd be personally curious to know what situation there is where one would *want* to do backend-sorting -- isn't it usually the case that client-side sorting is a big benefit because you get to offload some computation off of the server and onto client browsers? Just curious.

**Comment by mkielar** [comment]
I have a case where I present a result of a query which may contain several thousands of rows (depending on the search criteria). To save backend from overloading and out of memory errors, paging and infinite scroll are used, but this leads to a situation when the user sorts without having all of the rows on the frontend.

**Comment by drvic10k** [comment]
i suppose you don't want to replace the whole doSort implementation, because it also takes care of all the UI operations
so I added a possibility to provide custom sorting algorithm, that in your case will load the data from server and replace the rows

please, let me know, if this fits your needs
