### ISSUE TITLE
Avoid flipping order when switching between columns?

### ISSUE THREAD

**Issue by fsboehme** [drvic10k/bootstrap-sortable#70]
If I sort on column A (descending) and then sort on column B (descending) and then go back to sorting column A, it will flip the sort order on column A to ascending. 

Is there a way to avoid this behavior and always go with the data-firstsort order when sorting a column that isn't currently sorted? 

I would like only the second click (i.e. when re-sorting a column that is already sorted) to flip the sort order.

Cheers!

**Comment by drvic10k** [comment]
I don't think it's possible currently, but I also sometimes felt, that the behaviour is not completely right, so I agree with your complaint.

Would you expect to sort in the firs-sort order always, when it's not the current sort, or to use the last sort of that column, if it was sorted previously?

Do you think that what you expect is standard, or some spacial case? Because I'm a little affraid of changing the default behaviour, on the other hand I want to avoid having too many settings.

**Comment by fsboehme** [comment]
I would say the standard is to use the previous sorting. Right now, it's
always switching to the opposite sort order, which comes unexpected to me.
ᐧ

**Comment by Khrysller** [comment]
+1
