### ISSUE TITLE
Possible to use a button to sort?

### ISSUE THREAD

**Issue by Siiimple** [drvic10k/bootstrap-sortable#73]
This is an unusual questions, I realize.  

I have a client that wants to have the ability to push a button to sort specific elements with a row.  For example:  A "Pending" button would sort the contents with the word pending.  Rather than inputing the text in the filter. 

Thanks for any suggestions.

**Comment by drvic10k** [comment]
I don't understand what it means to sort just content with specific word

**Comment by Siiimple** [comment]
Instead of adding a word in the filter input area, they want a button for that word.  

So a "Pending" button would sort the rows that have the word "Pending".  Currently, if you the word "Pending" in the filter input, it will filter rows with "Pending" in them.  The client wants to have buttons, instead of the input.

**Comment by drvic10k** [comment]
well, there is a difference between sorting and filtering, do you mean sorting the "Pending" word at the beginning?

**Comment by Siiimple** [comment]
Yes, sorry for the confusion.

**Comment by drvic10k** [comment]
then it might be possible to "hack"
you can use the `data-value` attribute on the `<td>` elements instead of relying on automatic sorting according to the content
when your button is pressed, you can set the `data-value` for the required rows to guarantee that they will be sorted at the top and the apply the sorting
