### ISSUE TITLE
Sorting arrow

### ISSUE THREAD

**Issue by davidgrenier** [drvic10k/bootstrap-sortable#91]
I don't understand your doc, this is what I had to do to get the "arrow" pointing in the right direction:

```javascript
$(function () {
  $.bootstrapSortable({ sign: "arrow reversed" });
});
```

The reason people find this confusing is obviously because every other system out there uses the opposite direction than the default you put. The reason every other system out there uses the opposite direction is because what is considered to be shown isn't an arrow, it's a logo whose larger end corresponds to the largest value, analog to a less-than/greater-than mathematical symbol.

**Comment by drvic10k** [comment]
yeah, this is quite unfortunate, I had it in this way since the beginning and there was a discussion before I added this "reversed" option
the point is, that if I changed it, suddenly everyone would have it the opposite way after updating

I also did a brief research at that time and it is not so clear how it should be interpreted, one way is how you put it (long side of the triangle represents the bigger value), the other way is that the "arrow" points to the bigger value

**Comment by davidgrenier** [comment]
Oh I wasn't too concerned, pretty certain at this point I wouldn't make the change either.

But I never got how I could set it to reversed using $.bootstrapSortable(xxx, 'reversed'), that would simply not work.

**Comment by davidgrenier** [comment]
I also had figured the arrow class was required on the span, hence 'arrow reversed'

**Comment by drvic10k** [comment]
yeah, I should update the readme, it is a little outdated
I just tried to modify it everytime, but after the "2.0" when I changed the parameters to object it doesn't fit well anymore

**Comment by davidgrenier** [comment]
Cool, anyway glad I could figure it out. Aside from that... it was extremely easy to drop into our project... the effort is much appreciated.

**Comment by richardbrockie** [comment]
Thanks for the example of how to reverse the arrow direction. I was also confused by the instruction to use:
`$.bootstrapSortable(applyLast, 'reversed')`

For those like me not terribly familiar with javascript, adding the example at the top from @davidgrenier as a script after the bootstrap-sortable references got it working.
