### ISSUE TITLE
Sort not working

### ISSUE THREAD

**Issue by lcsqlpete** [drvic10k/bootstrap-sortable#94]
Just downloaded and installed but no sort arrows are appearing in my column headings and clicking on a column does not invoke a sort. 

Inside the <head> tag I have:
`<script src="dist/js/bootstrap-sortable.js"></script>`
`<script src="dist/js/moment.min.js"></script>`
`<link rel="stylesheet" href="dist/css/bootstrap-sortable.css">`

There are other js and css files inside the dist folder that are working OK

My `<table>` tag is:

`<table class="table table-striped table-bordered table-condensed sortable">`

It has `<thead>` and `<tbody>` tags.

The `<tbody>` html is created by a php script when the page is loaded:

`<tbody>`
`<?php include 'memberships-GetList.php'; ?>`
`</tbody>`

Could that be what is causing the problem?

**Comment by drvic10k** [comment]
If your table is created dynamically after the page load, you have to call
$.bootstrapSortable(bool); afterwards

Just downloaded and installed but no sort arrows are appearing in my column
headings and clicking on a column does not invoke a sort.

Inside the tag I have:

There are other js and css files inside the dist folder that are working OK

My
tag is:

It has
and tags.

The
html is created by a php script when the page is loaded:


<?php include 'memberships-GetList.php'; ?>

Could that be what is causing the problem?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/drvic10k/bootstrap-sortable/issues/94>, or mute the
thread
<https://github.com/notifications/unsubscribe/ADlKS55w3ZrFoj5dmjoIVbfqCwIlz9eCks5qHcIZgaJpZM4Iryqk>
.

**Comment by lcsqlpete** [comment]
Thanks.  Not a js expert so not sure how to do that. Could you give me som eexample code and where it should go in my html file?
Pete

**Comment by drvic10k** [comment]
sorry for late response, did you solve the problem?

I have no experience with php unfortunatelly, co I cannot give you any advice on this issue

**Comment by lcsqlpete** [comment]
Yes, figured it out.
Thanks,
Pete

**Comment by tonyxforce** [comment]
Hi, I don't know what I'm missing, but $.bootstrapSortable({ applyLast: true }) gives me "Uncaught TypeError: $.bootstrapSortable is not a function", what am I doing wrong?

**Comment by tiesont** [comment]
> Hi, I don't know what I'm missing, but . b o o t s t r a p S o r t a b l e ( a p p l y L a s t : t r u e ) g i v e s m e " U n c a u g h t T y p e E r r o r : .bootstrapSortable is not a function", what am I doing wrong?

Probably should post a new issue, but if you're literally using 

```js
.bootstrapSortable(applyLast: true);
```

then you're missing the `$` at the beginning:


```js
$.bootstrapSortable(applyLast: true);
```

**Comment by tonyxforce** [comment]
I'm sorry i figured it out i needed to include jQuery, i can close this now

**Comment by tiesont** [comment]
> I'm sorry i figured it out i needed to include jQuery, i can close this now

Well, no, you can't, because this issue was already closed 😆

**Comment by tonyxforce** [comment]
> > I'm sorry i figured it out i needed to include jQuery, i can close this now
> 
> Well, no, you can't, because this issue was already closed 😆
Oh sorry i thought commenting on an issue reopens it
